package model;
public class Admin {
    package com.taxicab.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

// ─── Inheritance:   Admin extends User ───────────────────────────────────────
// ─── Encapsulation: admin credentials secured inside this class ───────────────
// ─── Abstraction:   admin-only methods not accessible to regular users ─────────

    @Data
    @EqualsAndHashCode(callSuper = true)
    @NoArgsConstructor
    @Entity
    @Table(name = "admins")
    @PrimaryKeyJoinColumn(name = "user_id")
    public class Admin extends User {

        private String permissions = "ALL"; // e.g. "ALL", "READ_ONLY", "MANAGE_USERS"

        private LocalDateTime createdAt = LocalDateTime.now();

        // ─── Abstraction: admin-only action, hidden from regular users ─
        public String generateSystemReport() {
            return "System report generated by admin: " + getEmail();
        }

        // ─── Polymorphism: admin-specific authentication ──────────────
        @Override
        public String authenticate() {
            return "Admin login: " + getEmail() + " | Permissions: " + permissions;
        }
    }


}