package com.taxicab.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@Entity
@Table(name = "admins")
@PrimaryKeyJoinColumn(name = "user_id")
public class Admin extends User {

    private String permissions = "ALL"; 

    private LocalDateTime createdAt = LocalDateTime.now();

    
    public String generateSystemReport() {
        return "System report generated by admin: " + getEmail();
    }

    
    @Override
    public String authenticate() {
        return "Admin login: " + getEmail() +
                " | Permissions: " + permissions;
    }
}